
language: node_js

node_js:  
  - "12"

services:
  - postgresql

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/taxi-trip-test;

before_script:
  - psql -c 'create database taxi-trip-test;' -U postgres
  - psql -U postgres -d taxi-trip-test -a -f tables.sql


