language: node_js

node_js:  
  - "12"

services:
  - postgresql

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/taxi_trips_Tests;

before_script:
  - psql -c 'create database taxi_trips_Tests;' -U postgres
  - psql -U postgres -d taxi_trips_Tests -a -f tables.sq


